import { Wtf2Navigation } from '../../types';

export const navigation: Wtf2Navigation[] = [
  {
    id: 'archetype',
    title: 'archetype',
    translate: 'archetype',
    type: 'group',
    children: [
      {
        id: 'dashboard',
        title: 'dashboard',
        type: 'item',
        icon: 'email',
        url: '/archetype/dashboard',
      },
      {
        id: 'profile',
        title: 'profile',
        type: 'item',
        icon: 'email',
        url: '/archetype/profile',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      // {
      //     id: 'informationpage',
      //     title: 'informationpage',
      //     type: 'item',
      //     icon: 'email',
      //     url: '/archetype/informationpage',
      //     // badge: {
      //     //     title: '002',
      //     //     translate: 'A',
      //     //     bg: '#F44336',
      //     //     fg: '#FFFFFF',
      //     // },
      // },
      {
        id: 'actiontoolbar',
        title: 'actiontoolbar',
        type: 'item',
        icon: 'email',
        url: '/archetype/actiontoolbar',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'button',
        title: 'button',
        type: 'item',
        icon: 'email',
        url: '/archetype/button',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'input',
        title: 'input',
        type: 'item',
        icon: 'email',
        url: '/archetype/input',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'checkbox',
        title: 'checkbox',
        type: 'item',
        icon: 'email',
        url: '/archetype/checkbox',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'stepper',
        title: 'stepper',
        type: 'item',
        icon: 'email',
        url: '/archetype/add-customer',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'wtf2-grid',
        title: 'grid with checkbox',
        type: 'item',
        icon: 'email',
        url: '/archetype/wtf2-grid',
      },
      {
        id: 'wtf2-accordion-grid',
        title: 'accordion grid',
        type: 'item',
        icon: 'email',
        url: '/archetype/wtf2-accordion-grid',
      },
      {
        id: 'wtf2-grid-crud',
        title: 'grid crud operations',
        type: 'item',
        icon: 'email',
        url: 'archetype/wtf2-grid-crud',
      },
      {
        id: 'leftnav-with-scrollspy',
        title: 'leftnav with scrollspy',
        type: 'item',
        icon: 'email',
        url: '/archetype/leftnav-with-scrollspy',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'datepicker',
        title: 'datepicker',
        type: 'item',
        icon: 'email',
        url: '/archetype/datepicker',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'badgesandchips',
        title: 'badges and chips',
        type: 'item',
        icon: 'email',
        url: '/archetype/badgesandchips',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'formfield',
        title: 'form-field',
        type: 'item',
        icon: 'email',
        url: '/archetype/formfield',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'radio',
        title: 'radio',
        type: 'item',
        icon: 'email',
        url: '/archetype/radio',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'slider',
        title: 'slider',
        type: 'item',
        icon: 'email',
        url: '/archetype/slider',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'progressbar',
        title: 'progressbar',
        type: 'item',
        icon: 'email',
        url: '/archetype/progressbar',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'select',
        title: 'select',
        type: 'item',
        icon: 'email',
        url: '/archetype/select',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'accordion',
          title: 'accordion',
        type: 'item',
        icon: 'email',
        url: '/archetype/accordion',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'dialog',
        title: 'dialog',
        type: 'item',
        icon: 'email',
        url: '/archetype/dialog',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'list',
        title: 'list',
        type: 'item',
        icon: 'email',
        url: '/archetype/list',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'autocomplete',
        title: 'autocomplete',
        type: 'item',
        icon: 'email',
        url: '/archetype/autocomplete',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'card',
        title: 'card',
        type: 'item',
        icon: 'email',
        url: '/archetype/card',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'tabs',
        title: 'tabs',
        type: 'item',
        icon: 'email',
        url: '/archetype/tab',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'inform-expander',
        title: 'in-form expander',
        type: 'item',
        icon: 'email',
        url: '/archetype/inform-expander',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'pagelayout-carded-fullwidth-innerscroll',
        title: 'carded fullwidth innerscroll',
        type: 'item',
        icon: 'email',
        url: '/archetype/pagelayout-carded-fullwidth-innerscroll',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'pagelayout-carded-fullwidth',
        title: 'carded fullwidth default scroll',
        type: 'item',
        icon: 'email',
        url: '/archetype/pagelayout-carded-fullwidth',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'pagelayout-simple-fullwidth',
        title: 'simple fullwidth default scroll',
        type: 'item',
        icon: 'email',
        url: '/archetype/pagelayout-simple-fullwidth',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'pagelayout-simple-fullwidth-innerscroll',
        title: 'simple fullwidth innerscroll',
        type: 'item',
        icon: 'email',
        url: '/archetype/pagelayout-simple-fullwidth-innerscroll',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'pagelayout-left-sidenav-simple',
        title: 'left sidenav simple',
        type: 'item',
        icon: 'email',
        url: '/archetype/pagelayout-left-sidenav-simple',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'pagelayout-left-sidenav-carded',
        title: 'left sidenav carded',
        type: 'item',
        icon: 'email',
        url: '/archetype/pagelayout-left-sidenav-carded',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'wtf2-toster demo',
        title: 'toastr demo',
        type: 'item',
        icon: 'email',
        url: '/archetype/wtf2-toster-demo',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'wysiwyg-layout',
        title: 'wysiwyg layout',
        type: 'item',
        icon: 'email',
        url: '/archetype/wysiwyg-layout',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'currency-format',
        title: 'currency format',
        type: 'item',
        icon: 'email',
        url: '/archetype/currency-format',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'dashboard1',
        title: 'dashboard-one',
        type: 'item',
        icon: 'email',
        url: '/archetype/dashboard-one',
        // badge: {
        //   title: '002',
        //   translate: 'B',
        //   bg: '#F44336',
        //   fg: '#FFFFFF',
        // },
      },
      {
        id: 'bar',
        title: 'Bar Demo',
        type: 'item',
        icon: 'email',
        url: '/archetype/bar',
        // badge: {
        //   title: '002',
        //   translate: 'B',
        //   bg: '#F44336',
        //   fg: '#FFFFFF',
        // },
      },
      {
        id: 'pie',
        title: 'pie demo',
        type: 'item',
        icon: 'email',
        url: '/archetype/pie',
        // badge: {
        //   title: '002',
        //   translate: 'P',
        //   bg: '#F44336',
        //   fg: '#FFFFFF',
        // },
      },
      {
        id: 'line',
        title: 'line demo',
        type: 'item',
        icon: 'email',
        url: '/archetype/line',
        // badge: {
        //   title: '002',
        //   translate: 'L',
        //   bg: '#F44336',
        //   fg: '#FFFFFF',
        // },
      },
      {
        id: 'radar',
        title: 'radar and gauge',
        type: 'item',
        icon: 'email',
        url: '/archetype/radar',
        // badge: {
        //   title: '002',
        //   translate: 'R',
        //   bg: '#F44336',
        //   fg: '#FFFFFF',
        // },
      },
      // {
      //   id: 'donut',
      //   title: 'Donut Chart',
      //   type: 'item',
      //   icon: 'email',
      //   url: '/archetype/donut',
      //   badge: {
      //     title: '002',
      //     translate: 'D',
      //     bg: '#F44336',
      //     fg: '#FFFFFF',
      //   },
      // },
      // {
      //   id: 'stack',
      //   title: 'Stack Chart',
      //   type: 'item',
      //   icon: 'email',
      //   url: '/archetype/stack',
      //   badge: {
      //     title: '002',
      //     translate: 's',
      //     bg: '#F44336',
      //     fg: '#FFFFFF',
      //   },
      // },
      // {
      //   id: 'step',
      //   title: 'Step Chart',
      //   type: 'item',
      //   icon: 'email',
      //   url: '/archetype/step',
      //   badge: {
      //     title: '002',
      //     translate: 's',
      //     bg: '#F44336',
      //     fg: '#FFFFFF',
      //   },
      // },
      // {
      //   id: 'gauge',
      //   title: 'Gauge Chart',
      //   type: 'item',
      //   icon: 'email',
      //   url: '/archetype/gauge',
      //   badge: {
      //     title: '002',
      //     translate: 'G',
      //     bg: '#F44336',
      //     fg: '#FFFFFF',
      //   },
      // },
    ],
  },
];
