import { Wtf2Navigation } from '@wtf2/types';

export const navigation: Wtf2Navigation[] = [
  {
    id: 'archetype',
    title: 'ARCHETYPE',
    translate: 'NAV.ARCHETYPE',
    type: 'group',
    children: [
      {
        id: 'dashboard',
        title: 'Dashboard',
        translate: 'NAV.DASHBOARD',
        type: 'item',
        icon: 'dashboard',
        url: '/archetype/dashboard',
      },
      {
        id: 'profile',
        title: 'User Profile',
        translate: 'NAV.UserProfile',
        type: 'item',
        icon: 'email',
        url: '/archetype/profile',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'wtf2-page-layouts',
        title: 'Page Layouts',
        translate: 'NAV.LAYOUT',
        type: 'collapsable',
        icon: 'layers',
        children:[
          {
            id: 'Carded Fullwidth Innerscroll',
            title: 'cardedfullwidthinnerscroll',
            translate: 'NAV.ARCHETYPE',
            type: 'item',
            icon: 'layers',
            url: '/archetype/pagelayout-carded-fullwidth-innerscroll',
            // badge: {
            //     title: '002',
            //     translate: 'A',
            //     bg: '#F44336',
            //     fg: '#FFFFFF',
            // },
          },
          {
            id: 'pagelayout-carded-fullwidth',
            translate: 'NAV.cardedfullwidthdefaultscroll',
            title: 'Carded Fullwidth Default Scroll',
            type: 'item',
            icon: 'layers',
            url: '/archetype/pagelayout-carded-fullwidth',
            // badge: {
            //     title: '002',
            //     translate: 'A',
            //     bg: '#F44336',
            //     fg: '#FFFFFF',
            // },
          },
          {
            id: 'pagelayout-simple-fullwidth',
            translate: 'NAV.simplefullwidthdefaultscroll',
            title: 'Simple fullwidth default scroll',
            type: 'item',
            icon: 'layers',
            url: '/archetype/pagelayout-simple-fullwidth',
            // badge: {
            //     title: '002',
            //     translate: 'A',
            //     bg: '#F44336',
            //     fg: '#FFFFFF',
            // },
          },
          {
            id: 'pagelayout-simple-fullwidth-innerscroll',
            title: 'Simple full width innerscroll',
            translate: 'NAV.simplefullwidthinnerscroll',
            type: 'item',
            icon: 'layers',
            url: '/archetype/pagelayout-simple-fullwidth-innerscroll',
            // badge: {
            //     title: '002',
            //     translate: 'A',
            //     bg: '#F44336',
            //     fg: '#FFFFFF',
            // },
          },
          {
            id: 'pagelayout-left-sidenav-simple',
            title: 'Left sidenav Simple',
            translate: 'NAV.leftsidenavsimple',
            type: 'item',
            icon: 'layers',
            url: '/archetype/pagelayout-left-sidenav-simple',
            // badge: {
            //     title: '002',
            //     translate: 'A',
            //     bg: '#F44336',
            //     fg: '#FFFFFF',
            // },
          },
          {
            id: 'pagelayout-right-sidenav-simple',
            title: 'Right sidenav Simple',
            translate: 'NAV.rightsidenavsimple',
            type: 'item',
            icon: 'layers',
            url: '/archetype/pagelayout-right-sidenav-simple',
            // badge: {
            //     title: '002',
            //     translate: 'A',
            //     bg: '#F44336',
            //     fg: '#FFFFFF',
            // },
          },
          {
            id: 'pagelayout-left-sidenav-carded',
            title: 'Left sidenav Carded',
            translate: 'NAV.leftsidenavcarded',
            type: 'item',
            icon: 'email',
            url: '/archetype/pagelayout-left-sidenav-carded',
            // badge: {
            //     title: '002',
            //     translate: 'A',
            //     bg: '#F44336',
            //     fg: '#FFFFFF',
            // },
          },
          {
            id: 'pagelayout-right-sidenav-carded',
            title: 'Right sidenav Carded',
            translate: 'NAV.rightsidenavcarded',
            type: 'item',
            icon: 'layers',
            url: '/archetype/pagelayout-right-sidenav-carded',
            // badge: {
            //     title: '002',
            //     translate: 'A',
            //     bg: '#F44336',
            //     fg: '#FFFFFF',
            // },
          },
          {
            id: 'leftnav-with-scrollspy',
            title: 'Leftnav with Scrollspy',
            translate: 'NAV.leftnavwithscrollspy',
            type: 'item',
            icon: 'layers',
            url: '/archetype/leftnav-with-scrollspy',
            // badge: {
            //     title: '002',
            //     translate: 'A',
            //     bg: '#F44336',
            //     fg: '#FFFFFF',
            // },
          },
        ],
      },
      {
      id: 'form',
        title: 'Form in Expander and Dialog',
      translate: 'NAV.forminexpanderdialog',
      type: 'item',
      icon: 'email',
        url: '/archetype/expand-and-dialog',
      },
      // {
      //     id: 'informationpage',
      //     title: 'informationpage',
      //     type: 'item',
      //     icon: 'email',
      //     url: '/archetype/informationpage',
      //     // badge: {
      //     //     title: '002',
      //     //     translate: 'A',
      //     //     bg: '#F44336',
      //     //     fg: '#FFFFFF',
      //     // },
      // },
      {
        id: 'actiontoolbar',
        title: 'Action Toolbar',
        translate: 'NAV.actiontoolbar',
        type: 'item',
        icon: 'space_bar',
        url: '/archetype/actiontoolbar',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'button',
        title: 'Button',
        translate: 'NAV.button',
        type: 'item',
        icon: 'stop',
        url: '/archetype/button',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'input',
        title: 'Input',
        translate: 'NAV.input',
        type: 'item',
        icon: 'input',
        url: '/archetype/input',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'checkbox',
        title: 'Checkbox',
        translate: 'NAV.checkbox',
        type: 'item',
        icon: 'check_box',
        url: '/archetype/checkbox',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'stepper',
        title: 'Stepper',
        translate: 'NAV.stepper',
        type: 'item',
        icon: 'linear_scale',
        url: '/archetype/stepper',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'wtf2-grids',
        title: 'NAV.grid',
        type: 'collapsable',
        icon: 'email',
        children: [
          {
            id: 'wtf2-grid',
            title: 'NAV.gridwithcheckbox',
            type: 'item',
            icon: 'email',
            url: '/archetype/wtf2-grid',
          },
          {
            id: 'wtf2-accordion-grid',
            title: 'NAV.accordiongrid',
            type: 'item',
            icon: 'email',
            url: '/archetype/wtf2-accordion-grid',
          },
          {
            id: 'wtf2-grid-crud',
            title: 'NAV.gridcrudoperations',
            type: 'item',
            icon: 'email',
            url: 'archetype/wtf2-grid-crud',
          },
          {
            id: 'wtf2-nested-griddemo',
            title: 'NAV.nestedgrid',
            type: 'item',
            icon: 'email',
            url: '/archetype/wtf2-nested-grid',
          },
          {
            id: 'wtf2-draggable-griddemo',
            title: 'NAV.draggblegrid',
            type: 'item',
            icon: 'email',
            url: '/archetype/wtf2-draggable-grid'
          }
        ]
      },
      {
        id: 'datepicker',
        title: 'datepicker',
        translate: 'NAV.datepicker',
        type: 'item',
        icon: 'calendar_today',
        url: '/archetype/datepicker',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'badgesandchips',
        title: 'Badges and Chips',
        translate: 'NAV.badgesandchips',
        type: 'item',
        icon: 'fiber_manual_record',
        url: '/archetype/badgesandchips',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'formfield',
        title: 'Form-Field',
        translate: 'NAV.formfield',
        type: 'item',
        icon: 'forum',
        url: '/archetype/formfield',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'radio',
        title: 'Radio',
        translate: 'NAV.radio',
        type: 'item',
        icon: 'radio_button_checked',
        url: '/archetype/radio',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'richtext',
        title: 'Rich Text Editor',
        translate: 'NAV.richtexteditor',
        type: 'item',
        icon: 'wrap_text',
        url: '/archetype/rich-text-editor',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'slider',
        title: 'Slider',
        translate: 'NAV.slider',
        type: 'item',
        icon: 'slideshow',
        url: '/archetype/slider',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'progressbar',
        title: 'Progressbar',
        translate: 'NAV.progressbar',
        type: 'item',
        icon: 'more_horiz',
        url: '/archetype/progressbar',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'select',
        title: 'Select',
        translate: 'NAV.select',
        type: 'item',
        icon: 'select_all',
        url: '/archetype/select',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'accordion',
        title: 'Accordion',
        translate: 'NAV.accordion',
        type: 'item',
        icon: 'view_list',
        url: '/archetype/accordion',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'dialog',
        title: 'Dialog',
        translate: 'NAV.dialog',
        type: 'item',
        icon: 'web_asset',
        url: '/archetype/dialog',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'dialog-box',
        title: 'Dialog Box View',
        translate: 'NAV.dialogboxview',
        type: 'item',
        icon: 'email',
        url: '/archetype/dialog-box-view',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
      // },
      },
      {
        id: 'list',
        title: 'List',
        translate: 'NAV.list',
        type: 'item',
        icon: 'list',
        url: '/archetype/list',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'tree',
        title: 'Tree',
        // translate: 'NAV.list',
        type: 'item',
        icon: 'list',
        url: '/archetype/tree',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'autocomplete',
        title: 'Autocomplete',
        translate: 'NAV.autocomplete',
        type: 'item',
        icon: 'wb_auto',
        url: '/archetype/autocomplete',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'card',
        title: 'Card',
        translate: 'NAV.card',
        type: 'item',
        icon: 'crop_square',
        url: '/archetype/card',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'tabs',
        title: 'Tabs',
        translate: 'NAV.tabs',
        type: 'item',
        icon: 'tab',
        url: '/archetype/tab',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'inform-expander',
        title: 'In-form Expander',
        translate: 'NAV.informexpander',
        type: 'item',
        icon: 'filter_frames',
        url: '/archetype/inform-expander',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'carousel',
        title: 'Carousel',
        translate: 'NAV.carousel',
        type: 'item',
        icon: 'view_carousel',
        url: '/archetype/carousel',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'wtf2-spinner-demo',
        title: 'Spinner Demo',
        translate: 'NAV.spinnerdemo',
        type: 'item',
        icon: 'settings_input_svideo',
        url: '/archetype/wtf2-spinner-demo-component',
      },
      {
        id: 'wtf2-toster demo',
        title: 'Toastr Demo',
        translate: 'NAV.toastrdemo',
        type: 'item',
        icon: 'label',
        url: '/archetype/wtf2-toster-demo',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'wysiwyg-layout',
        title: 'Wysiwyg Layout',
        translate: 'NAV.wysiwyglayout',
        type: 'item',
        icon: 'edit_attributes',
        url: '/archetype/wysiwyg-layout',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      {
        id: 'currency-format',
        title: 'Currency Format',
        translate: 'NAV.currencyformat',
        type: 'item',
        icon: 'monetization_on',
        url: '/archetype/currency-format',
        // badge: {
        //     title: '002',
        //     translate: 'A',
        //     bg: '#F44336',
        //     fg: '#FFFFFF',
        // },
      },
      // {
      //   id: 'tree',
      //   title: 'tree',
      //   type: 'item',
      //   icon: 'email',
      //   url: '/archetype/tree',
      //   // badge: {
      //   //     title: '002',
      //   //     translate: 'A',
      //   //     bg: '#F44336',
      //   //     fg: '#FFFFFF',
      //   // },
      // },
      {
        id: 'dashboard1',
        title: 'Dashboard-one',
        translate: 'NAV.dashboardone',
        type: 'item',
        icon: 'email',
        url: '/archetype/dashboard-one',
        // badge: {
        //   title: '002',
        //   translate: 'B',
        //   bg: '#F44336',
        //   fg: '#FFFFFF',
      // },
      },
      {
        id: 'bar',
        title: 'demobar',
        translate: 'NAV.demobar',
        type: 'item',
        icon: 'insert_chart_outlined',
        url: '/archetype/bar',
        // badge: {
        //   title: '002',
        //   translate: 'B',
        //   bg: '#F44336',
        //   fg: '#FFFFFF',
        // },
      },
      {
        id: 'pie',
        title: 'Pie demo',
        translate: 'NAV.piedemo',
        type: 'item',
        icon: 'pie_chart',
        url: '/archetype/pie',
        // badge: {
        //   title: '002',
        //   translate: 'P',
        //   bg: '#F44336',
        //   fg: '#FFFFFF',
        // },
      },
      {
        id: 'line',
        title: 'Line demo',
        translate: 'NAV.linedemo',
        type: 'item',
        icon: 'show_chart',
        url: '/archetype/line',
        // badge: {
        //   title: '002',
        //   translate: 'L',
        //   bg: '#F44336',
        //   fg: '#FFFFFF',
        // },
      },
      {
        id: 'radar',
        title: 'radar and gauge',
        translate: 'NAV.radarandgauge',
        type: 'item',
        icon: 'looks',
        url: '/archetype/radar',
        // badge: {
        //   title: '002',
        //   translate: 'R',
        //   bg: '#F44336',
        //   fg: '#FFFFFF',
        // },
      },
      {
        id: 'elevation-demo',
        title: 'Elevation',
        translate: 'NAV.elevation',
        type: 'item',
        icon: 'filter_none',
        url: '/archetype/elevation-demo',
        // badge: {
        //   title: '002',
        //   translate: 'R',
        //   bg: '#F44336',
        //   fg: '#FFFFFF',
        // },
      },
      {
        id: 'wtf2-quote demo',
        title: 'Wtf2-Quote',
        type: 'item',
        icon: 'email',
        url: '/archetype/wtf2-quote-demo',
    },
      {
        id: 'error-404',
        title: 'error-404',
        type: 'item',
        icon: 'error',
        url: '/archetype/error-404',
    },
      {
        id: 'error-500',
        title: 'error-500',
        type: 'item',
        icon: 'error',
        url: '/archetype/error-500',
    },
    {
        id: 'search',
        title: 'search',
        type: 'item',
        icon: 'search',
        url: '/archetype/search',
        // badge: {
        //   title: '002',
        //   translate: 'R',
        //   bg: '#F44336',
        //   fg: '#FFFFFF',
        // },
      },
      // {
      //   id: 'donut',
      //   title: 'Donut Chart',
      //   type: 'item',
      //   icon: 'email',
      //   url: '/archetype/donut',
      //   badge: {
      //     title: '002',
      //     translate: 'D',
      //     bg: '#F44336',
      //     fg: '#FFFFFF',
      //   },
      // },
      // {
      //   id: 'stack',
      //   title: 'Stack Chart',
      //   type: 'item',
      //   icon: 'email',
      //   url: '/archetype/stack',
      //   badge: {
      //     title: '002',
      //     translate: 's',
      //     bg: '#F44336',
      //     fg: '#FFFFFF',
      //   },
      // },
      // {
      //   id: 'step',
      //   title: 'Step Chart',
      //   type: 'item',
      //   icon: 'email',
      //   url: '/archetype/step',
      //   badge: {
      //     title: '002',
      //     translate: 's',
      //     bg: '#F44336',
      //     fg: '#FFFFFF',
      //   },
      // },
      // {
      //   id: 'gauge',
      //   title: 'Gauge Chart',
      //   type: 'item',
      //   icon: 'email',
      //   url: '/archetype/gauge',
      //   badge: {
      //     title: '002',
      //     translate: 'G',
      //     bg: '#F44336',
      //     fg: '#FFFFFF',
      //   },
      // },
    ],
  },
];
